name: Publish Showrunner Common
on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      #Setup .npmrc file to publish to GitHub Packages
      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@coderatparadise'
      - name: Use yarn Zero Install Cache
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
             ${{ runner.os }}-yarn-
      - run: |
          echo '::echo::on'
          echo "::set-output name=scope::$(yarn config get npmScopes)"
      - name: Setup .yarnrc.yml
        run: |
            yarn config set npmScopes.coderatparadise.npmAuthToken $NODE_AUTH_TOKEN
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: |
          echo '::echo::on'
          echo "::set-output name=scope::$(yarn config get npmScopes)"
      - run: yarn
      - run: yarn lint
      - run: yarn build
      - run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}